// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3UnNf9RkNsUSmW514quInONk30gZ63mU',
    appId: '1:1035139460780:web:1af44aeaea581029a1f909',
    messagingSenderId: '1035139460780',
    projectId: 'mobile-project-axid',
    authDomain: 'mobile-project-axid.firebaseapp.com',
    storageBucket: 'mobile-project-axid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPu7Got8stBNe4o-cMCUHhDXcF9wRLQy4',
    appId: '1:1035139460780:android:9e3d1ba279ce9a4da1f909',
    messagingSenderId: '1035139460780',
    projectId: 'mobile-project-axid',
    storageBucket: 'mobile-project-axid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvezF2oIvIs-k0PD_Gn_n10pY6S3_jAg',
    appId: '1:1035139460780:ios:d5d6846a4dbe3805a1f909',
    messagingSenderId: '1035139460780',
    projectId: 'mobile-project-axid',
    storageBucket: 'mobile-project-axid.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvezF2oIvIs-k0PD_Gn_n10pY6S3_jAg',
    appId: '1:1035139460780:ios:d5d6846a4dbe3805a1f909',
    messagingSenderId: '1035139460780',
    projectId: 'mobile-project-axid',
    storageBucket: 'mobile-project-axid.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3UnNf9RkNsUSmW514quInONk30gZ63mU',
    appId: '1:1035139460780:web:84d193fa74c015efa1f909',
    messagingSenderId: '1035139460780',
    projectId: 'mobile-project-axid',
    authDomain: 'mobile-project-axid.firebaseapp.com',
    storageBucket: 'mobile-project-axid.appspot.com',
  );

}